import type { Account } from "./types"

export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    name: "Stripe Inc.",
    domain: "stripe.com",
    mrr: 18500,
    healthScore: 94,
    healthStatus: "good",
    ownerName: "Jason UXUI",
    ownerEmail: "jason@company.com",
    renewalDate: "2026-12-15",
    tier: "enterprise",
    expansionOpportunity: true,
  },
  {
    id: "acc-2",
    name: "Cyberdyne Systems",
    domain: "cyberdyne.ru",
    mrr: 7200,
    healthScore: 48,
    healthStatus: "poor",
    ownerName: "Jason UXUI",
    ownerEmail: "jason@company.com",
    renewalDate: "2026-09-01",
    tier: "mid-market",
    expansionOpportunity: false,
  },
  {
    id: "acc-3",
    name: "Hooli Corp",
    domain: "hooli.xyz",
    mrr: 12000,
    healthScore: 82,
    healthStatus: "good",
    ownerName: "Sarah Connor",
    ownerEmail: "sarah@company.com",
    renewalDate: "2026-11-20",
    tier: "enterprise",
    expansionOpportunity: true,
  },
  {
    id: "acc-4",
    name: "Acme Corporation",
    domain: "acme.com",
    mrr: 3500,
    healthScore: 71,
    healthStatus: "fair",
    ownerName: "John Doe",
    ownerEmail: "john@company.com",
    renewalDate: "2027-02-10",
    tier: "smb",
    expansionOpportunity: false,
  },
  {
    id: "acc-5",
    name: "Initech LLC",
    domain: "initech.com",
    mrr: 2100,
    healthScore: 63,
    healthStatus: "fair",
    ownerName: "Sarah Connor",
    ownerEmail: "sarah@company.com",
    renewalDate: "2026-08-30",
    tier: "smb",
    expansionOpportunity: true,
  },
]
