import type { KnowledgeArticleInsightFixture } from "@/lib/knowledge-base/insights"

export const knowledgeArticleInsightFixtures: Record<
  string,
  KnowledgeArticleInsightFixture
> = {
  "kb-billing-seat-update": {
    matching: {
      categoryLabel: "Subscription",
      testQuery: "how do i add a user to my plan",
      testResult: "Matches via seat",
      signals: [
        {
          id: "seat",
          signal: "seat",
          source: "manual",
          matches30d: 140,
          openRate: 71,
          status: "Strong match",
          action: "mute",
          matchTerms: [
            "add a user",
            "add user",
            "add user to plan",
            "user to my plan",
          ],
        },
        {
          id: "subscription",
          signal: "subscription",
          source: "manual",
          matches30d: 88,
          openRate: 64,
          status: "Healthy",
          action: "mute",
        },
        {
          id: "add-team-member",
          signal: "add team member",
          source: "auto",
          matches30d: 54,
          openRate: 74,
          status: "Emerging phrase",
          action: "mute",
        },
        {
          id: "billing",
          signal: "billing",
          source: "manual",
          matches30d: 19,
          openRate: 31,
          status: "Low intent",
          action: "mute",
        },
        {
          id: "invoice",
          signal: "invoice",
          source: "manual",
          matches30d: 2,
          openRate: 0,
          status: "No recent opens",
          action: "remove",
          isMuted: true,
        },
        {
          id: "how-to-add-user",
          signal: "how to add user",
          source: "suggested",
          matches30d: 31,
          openRate: null,
          status: "Missed search",
          action: "add",
          missedSearchesLabel: "missed searches",
        },
        {
          id: "upgrade-plan",
          signal: "upgrade plan",
          source: "suggested",
          matches30d: 17,
          openRate: null,
          status: "Missed search",
          action: "add",
          missedSearchesLabel: "missed searches",
        },
      ],
    },
    linkedTickets: {
      summary: "21 tickets - latest 12 days ago",
      rows: [
        {
          id: "t-013-read-still-filed",
          ticketId: "t-013",
          ticketNumber: "#TC-013",
          subject: "Seat transfer request between subsidiaries before renewal",
          type: "task",
          status: "resolved",
          priority: "medium",
          context: "read-still-filed",
          customer: "Santi Cazorla",
        },
        {
          id: "t-015-read-still-filed",
          ticketId: "t-015",
          ticketNumber: "#TC-015",
          subject: "Plan phased seat expansion for the next quarter launch",
          type: "task",
          status: "pending",
          priority: "medium",
          context: "read-still-filed",
          customer: "Jerome Bell",
        },
        {
          id: "t-006-linked-by-agent",
          ticketId: "t-006",
          ticketNumber: "#TC-006",
          subject: "Customer asks for a rollout plan for conditional workflows",
          type: "task",
          status: "resolved",
          priority: "low",
          context: "linked-by-agent",
          customer: "Courtney Henry",
        },
        {
          id: "t-018-linked-by-agent",
          ticketId: "t-018",
          ticketNumber: "#TC-018",
          subject: "Need audit log retention options for the enterprise rollout",
          type: "task",
          status: "pending",
          priority: "high",
          context: "linked-by-agent",
          customer: "Esther Howard",
        },
      ],
    },
    feedback: {
      averageRating: 3.7,
      reviewCount: 11,
      helpfulVotes: 188,
      notHelpfulVotes: 22,
      negativeComments: [
        {
          id: "neg-billing-cycle",
          vote: "not-helpful",
          age: "8 days ago",
          body: "Doesn't explain what happens to billing mid-cycle. I still don't know if I get charged now or next month.",
          source: "Help center",
          authorName: "Priya Raman",
          authorInitials: "PR",
          rating: 2,
        },
        {
          id: "neg-old-ui",
          vote: "not-helpful",
          age: "12 days ago",
          body: "Screenshots are from the old UI, the Seats button isn't where the article says.",
          source: "In-ticket suggestion",
          authorName: "Michael Tran",
          authorInitials: "MT",
          rating: 3,
        },
        {
          id: "neg-permission-note",
          vote: "not-helpful",
          age: "16 days ago",
          body: "It should mention which admin permissions are required before customers try to add seats.",
          source: "Help center",
          authorName: "Olivia Grant",
          authorInitials: "OG",
          rating: 3,
        },
        {
          id: "neg-tax-question",
          vote: "not-helpful",
          age: "21 days ago",
          body: "The pricing step is clear, but I still had to ask support how taxes are handled.",
          source: "Widget",
          authorName: "Hiro Tanaka",
          authorInitials: "HT",
          rating: 2,
        },
      ],
      helpfulComments: [
        {
          id: "pos-clear",
          vote: "helpful",
          age: "15 days ago",
          body: "Clear and quick, solved it in 2 minutes.",
          source: "Widget",
          authorName: "Sarah Kim",
          authorInitials: "SK",
          rating: 5,
        },
        {
          id: "pos-fast-pricing",
          vote: "helpful",
          age: "18 days ago",
          body: "Super helpful. Solved my problem in under 2 minutes.",
          source: "Help center",
          authorName: "James Lee",
          authorInitials: "JL",
          rating: 5,
        },
        {
          id: "pos-pricing-logic",
          vote: "helpful",
          age: "20 days ago",
          body: "Answered my question but I had to read it twice to understand the pricing logic.",
          source: "Widget",
          authorName: "Fatima Ali",
          authorInitials: "FA",
          rating: 3,
        },
        {
          id: "pos-admin-steps",
          vote: "helpful",
          age: "22 days ago",
          body: "The admin steps matched our workspace exactly and made it easy to update the subscription.",
          source: "Help center",
          authorName: "Andre Silva",
          authorInitials: "AS",
          rating: 5,
        },
        {
          id: "pos-seat-count",
          vote: "helpful",
          age: "24 days ago",
          body: "I liked that it called out how to confirm the final seat count before checkout.",
          source: "Widget",
          authorName: "Mei Wong",
          authorInitials: "MW",
          rating: 4,
        },
        {
          id: "pos-renewal-note",
          vote: "helpful",
          age: "26 days ago",
          body: "The note about renewals helped our finance lead understand when the change takes effect.",
          source: "In-ticket suggestion",
          authorName: "Noah Bell",
          authorInitials: "NB",
          rating: 4,
        },
        {
          id: "pos-easy-share",
          vote: "helpful",
          age: "29 days ago",
          body: "Short enough to share with our workspace owner without rewriting the instructions.",
          source: "Widget",
          authorName: "Leah Stone",
          authorInitials: "LS",
          rating: 5,
        },
        {
          id: "pos-no-ticket",
          vote: "helpful",
          age: "31 days ago",
          body: "This saved me from opening a support ticket during our team expansion.",
          source: "Help center",
          authorName: "Victor Chen",
          authorInitials: "VC",
          rating: 5,
        },
      ],
    },
    searchDiscovery: {
      queries: [
        { id: "q-seat-add", query: "how to add user seats", ctr: 38, views: 142 },
        { id: "q-seat-limit", query: "subscription seat limit", ctr: 29, views: 97 },
        { id: "q-team-billing", query: "add team member billing", ctr: 44, views: 83 },
        { id: "q-pro-plan", query: "increase seats pro plan", ctr: 21, views: 61 },
        { id: "q-seat-pricing", query: "seat pricing per user", ctr: 33, views: 48 },
      ],
    },
  },
  "kb-card-charge-failed": {
    feedback: {
      averageRating: 3.4,
      reviewCount: 3,
      helpfulVotes: 125,
      notHelpfulVotes: 42,
      negativeComments: [
        {
          id: "neg-retry-window",
          vote: "not-helpful",
          age: "3 days ago",
          body: "The retry timing is still unclear. I need to know exactly when the next card attempt happens.",
          source: "Help center",
          authorName: "Ava Morgan",
          authorInitials: "AM",
          rating: 2,
        },
        {
          id: "neg-grace-period",
          vote: "not-helpful",
          age: "6 days ago",
          body: "It mentions grace periods but does not say what customers see when access is limited.",
          source: "In-ticket suggestion",
          authorName: "Noah Patel",
          authorInitials: "NP",
          rating: 3,
        },
      ],
      helpfulComments: [
        {
          id: "pos-card-fix",
          vote: "helpful",
          age: "5 days ago",
          body: "The card decline checklist helped me fix the renewal before support had to step in.",
          source: "Widget",
          authorName: "Lena Brooks",
          authorInitials: "LB",
          rating: 5,
        },
      ],
    },
    searchDiscovery: {
      queries: [
        { id: "q-card-retry", query: "when will card retry", ctr: 36, views: 95 },
        { id: "q-renewal-failed", query: "renewal payment failed", ctr: 41, views: 84 },
        { id: "q-grace-access", query: "grace period access", ctr: 24, views: 58 },
        { id: "q-update-card", query: "update default card", ctr: 31, views: 47 },
      ],
    },
  },
}
