import type { InboxThread } from "./types"

export const mockInboxThreads: InboxThread[] = [
  {
    id: "th-1",
    customerName: "Sarah Jenkins",
    customerEmail: "sarah.j@acme.com",
    subject: "Unable to sync Salesforce accounts in integration panel",
    channel: "email",
    status: "new",
    teaser: "Email, chat, in-app, and form messages flow into one queue. I keep getting a 403 authorization error when clicking the test connection button.",
    updatedAt: "10m ago",
    assignee: null,
    messages: [
      {
        id: "msg-1-1",
        senderName: "Sarah Jenkins",
        senderEmail: "sarah.j@acme.com",
        role: "customer",
        content: "Hi support team,\n\nI am trying to configure the Salesforce sync under settings, but every time I click 'Test Connection' after pasting my client credentials, I get a 403 Forbidden error. Can you verify if my account has the required API scopes enabled?\n\nThanks,\nSarah",
        timestamp: "10m ago",
      },
    ],
  },
  {
    id: "th-2",
    customerName: "David Miller",
    customerEmail: "d.miller@vertex.io",
    subject: "Urgent: Billing discrepancy on invoice #INV-2026-08",
    channel: "chat",
    status: "open",
    teaser: "We were charged for 45 active seats this month but our admin dashboard only shows 32 active seats. Please adjust.",
    updatedAt: "1h ago",
    assignee: {
      name: "Jason UXUI",
      email: "jason@company.com",
    },
    messages: [
      {
        id: "msg-2-1",
        senderName: "David Miller",
        senderEmail: "d.miller@vertex.io",
        role: "customer",
        content: "Hello! We noticed a discrepancy on our latest invoice. We were charged for 45 seats but only 32 are active. Can we get this credited?",
        timestamp: "1h ago",
      },
      {
        id: "msg-2-2",
        senderName: "Jason UXUI",
        role: "agent",
        content: "Hi David, thanks for reaching out. Let me look up your billing history and compare the seat allocation. I'll get this sorted out for you shortly.",
        timestamp: "45m ago",
      },
      {
        id: "msg-2-3",
        senderName: "David Miller",
        senderEmail: "d.miller@vertex.io",
        role: "customer",
        content: "Perfect, thank you! Standing by.",
        timestamp: "40m ago",
      },
    ],
  },
  {
    id: "th-3",
    customerName: "Elena Rostova",
    customerEmail: "elena@cyberdyne.ru",
    subject: "API Rate Limit exceeded during database migration",
    channel: "slack",
    status: "pending",
    teaser: "Our migration scripts are failing due to HTTP 429 Rate Limit Exceeded. We need a temporary limit boost.",
    updatedAt: "2h ago",
    assignee: {
      name: "Jason UXUI",
      email: "jason@company.com",
    },
    messages: [
      {
        id: "msg-3-1",
        senderName: "Elena Rostova",
        senderEmail: "elena@cyberdyne.ru",
        role: "customer",
        content: "Hey, we are currently running a database migration and hitting rate limits. Can you temporarily boost our API threshold for the next 24 hours?",
        timestamp: "2h ago",
      },
      {
        id: "msg-3-2",
        senderName: "Jason UXUI",
        role: "agent",
        content: "Hello Elena, I've requested a temporary rate limit lift of 5x from our infrastructure team. They are reviewing it now. I'll update you as soon as it's active.",
        timestamp: "1.5h ago",
      },
    ],
  },
  {
    id: "th-4",
    customerName: "Marcus Vance",
    customerEmail: "marcus@hooli.xyz",
    subject: "Requesting copy of SOC2 compliance report",
    channel: "form",
    status: "resolved",
    teaser: "Our security team requires the latest SOC2 Type II report for our annual vendor review.",
    updatedAt: "1d ago",
    assignee: {
      name: "Support Admin",
      email: "admin@company.com",
    },
    messages: [
      {
        id: "msg-4-1",
        senderName: "Marcus Vance",
        senderEmail: "marcus@hooli.xyz",
        role: "customer",
        content: "Hello, could you please share your latest SOC2 compliance report? Our audit team needs it.",
        timestamp: "1d ago",
      },
      {
        id: "msg-4-2",
        senderName: "Support Admin",
        role: "agent",
        content: "Hi Marcus, I have sent the SOC2 Type II report to your email on file along with our NDA addendum. Let me know if you need anything else!",
        timestamp: "18h ago",
      },
      {
        id: "msg-4-3",
        senderName: "Marcus Vance",
        senderEmail: "marcus@hooli.xyz",
        role: "customer",
        content: "Received, thank you for the fast response!",
        timestamp: "17h ago",
      },
    ],
  },
]
